---
version: "3.3"
services:

  nginx:
    image: nginx:stable-alpine
    container_name: carlbennett-api-nginx
    restart: always
    depends_on:
      - mariadb
      - php
    volumes:
      - ./etc/docker/nginx-vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - /usr/share/GeoIP/GeoLite2-City.mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
    ports:
      - "8080:80"

  php:
    build: './etc/docker/php'
    container_name: carlbennett-api-php
    restart: always
    volumes:
      - mariadb-vol-1:/var/lib/mysql/:Z
      - .:/var/www/html
      - /usr/share/GeoIP/GeoLite2-City.mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
    expose:
      - "9000"

  mariadb:
    image: mariadb:10.7
    container_name: carlbennett-api-mariadb
    restart: always
    volumes:
      - mariadb-vol-1:/var/lib/mysql/:Z
    expose:
      - "3306"
    environment:
      - MARIADB_DATABASE=carlbennett_api_docker
      - MARIADB_ROOT_PASSWORD=carlbennett_api_docker_rootpw420
      - MARIADB_USER=carlbennett_api_docker
      - MARIADB_PASSWORD=carlbennett_api_docker
      - MARIADB_AUTO_UPGRADE=yes
      - MARIADB_DISABLE_UPGRADE_BACKUP=yes

volumes:
  mariadb-vol-1:
